[req]
default_bits       = 2048
default_md         = sha256
distinguished_name = req_distinguished_name
req_extensions     = v3_req
prompt             = no

[req_distinguished_name]
C  = BE
ST = Antwerp
L  = Brecht
O  = RiddlerDev
CN = localhost

# USED DURING CSR GENERATION (Safe for requests)
[v3_req]
basicConstraints = CA:FALSE
keyUsage         = digitalSignature, keyEncipherment
subjectAltName   = @alt_names

# USED DURING SIGNING ONLY (Safe for CA processing)
[v3_ca_sign]
authorityKeyIdentifier = keyid,issuer
basicConstraints       = CA:FALSE
keyUsage               = digitalSignature, keyEncipherment
subjectAltName         = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = 127.0.0.1
